//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbgSvcConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VbsCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VbsCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbgSvcConfiguration.VbsCode", typeof(VbsCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const ACTIONS_NEED_CLR_EXCEPTION_TYPES = False
        ///Const ACTIONS_NEED_CLR_EXCEPTION_MSGS = False
        ///Const MAX_NATIVE_EXCEPTION_STACKS_PER_SECOND = 30
        ///Const MAX_NATIVE_EXCEPTION_STACKS_PER_EXCEPTION_TYPE = 100
        ///Const MAX_VARIANTS_PER_EXCEPTION_TYPE = 20
        ///Const MAX_CLR_EXCEPTION_DETAILS_PER_SECOND = 30
        ///Const MAX_CLR_EXCEPTION_STACKS_PER_SECOND = 20
        ///Const MAX_CLR_EXCEPTION_STACKS_PER_EXCEPTION_TYPE = 10
        ///Const MAX_CLR_EXCEPTION_STACKS_TOTAL = 100
        ///Const CRASH_RULE_LOGGING_ENABLED = True
        ///Const INCLUDE_EXCEPTION_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PerExeTemplate {
            get {
                return ResourceManager.GetString("PerExeTemplate", resourceCulture);
            }
        }
    }
}
